import type { FNSLocation } from "@/lib/types";

export const FNS_LOCATIONS: FNSLocation[] = [
  {
    id: "torrance-ca",
    name: "FNS - Torrance, CA",
    address: "1545 Francisco St., Torrance, CA 90501, US",
    city: "Torrance",
    state: "CA",
    type: "Office",
  },
  {
    id: "duluth-ga",
    name: "FNS - Duluth, GA",
    address: "3235 Satellite Blvd. Bldg. 400, Suite #625, Duluth, GA 30096, US",
    city: "Duluth",
    state: "GA",
    type: "Office",
  },
  {
    id: "morrow-ga",
    name: "FNS - Morrow, GA",
    address: "7135 Southlake Parkway, Suite A, Morrow, GA 30260, US",
    city: "Morrow",
    state: "GA",
    type: "Warehouse",
  },
  {
    id: "atlanta-ga",
    name: "FNS - Atlanta, GA",
    address: "4370 Old Dixie Rd, Suite C, Atlanta, GA 30354, US",
    city: "Atlanta",
    state: "GA",
    type: "Logistics Hub",
  },
  {
    id: "franklin-park-il",
    name: "FNS - Franklin Park, IL",
    address: "1061 Seymour Ave., Suite 100, Franklin Park, IL 60131, US",
    city: "Franklin Park",
    state: "IL",
    type: "Office",
  },
  {
    id: "flower-mound-tx",
    name: "FNS - Flower Mound, TX",
    address: "2201 Spinks Rd, Flower Mound, TX 75028, US",
    city: "Flower Mound",
    state: "TX",
    type: "Logistics Hub",
  },
  {
    id: "romeoville-il",
    name: "FNS - Romeoville, IL",
    address: "5 Greenwood, Romeoville, IL 60446, US",
    city: "Romeoville",
    state: "IL",
    type: "Warehouse",
  },
  {
    id: "euless-tx",
    name: "FNS - Euless / DFW, TX",
    address: "3001 W Airfield Dr, Suite 300, Euless, TX 75261, US",
    city: "Euless",
    state: "TX",
    type: "Logistics Hub",
  },
  {
    id: "deer-park-tx",
    name: "FNS - Deer Park, TX",
    address: "2902 13th Street, Suite 100, Deer Park, TX 77536, US",
    city: "Deer Park",
    state: "TX",
    type: "Office",
  },
  {
    id: "houston-tx-8511",
    name: "FNS - Houston, TX / Monroe 8511",
    address: "8511 Monroe Rd, Houston, TX 77061, US",
    city: "Houston",
    state: "TX",
    type: "Logistics Hub",
  },
  {
    id: "houston-tx-8505",
    name: "FNS - Houston, TX / Monroe 8505",
    address: "8505 Monroe Rd, Houston, TX 77061, US",
    city: "Houston",
    state: "TX",
    type: "Logistics Hub",
  },
  {
    id: "carson-ca",
    name: "FNS - Carson, CA",
    address: "18420-18620 Harmon Ave, Carson, CA 90746, US",
    city: "Carson",
    state: "CA",
    type: "Warehouse",
  },
  {
    id: "san-diego-ca",
    name: "FNS - San Diego, CA",
    address: "6855 Calle de Linea, San Diego, CA 92154, US",
    city: "San Diego",
    state: "CA",
    type: "Logistics Hub",
  },
  {
    id: "mcallen-tx",
    name: "FNS - McAllen, TX",
    address: "3600 Formosa Ave, Building N, McAllen, TX 78503, US",
    city: "McAllen",
    state: "TX",
    type: "Logistics Hub",
  },
  {
    id: "kansas-city-mo",
    name: "FNS - Kansas City, MO",
    // Corrected per the FNS main directory; the previous Silverbell Rd
    // address belongs to the Lake Orion, MI branch.
    address: "14301 NE 41st St, Kansas City, MO 64161, US",
    city: "Kansas City",
    state: "MO",
    type: "Office",
  },
  {
    id: "somerset-nj",
    name: "FNS - New Jersey / Somerset",
    address: "400 Pierce St., Somerset, NJ 08873, US",
    city: "Somerset",
    state: "NJ",
    type: "Office",
  },
  {
    id: "moonachie-nj",
    name: "FNS - New Jersey / Moonachie",
    address: "245 W Commercial Ave, Moonachie, NJ 07074, US",
    city: "Moonachie",
    state: "NJ",
    type: "Warehouse",
  },
  {
    id: "ravenna-oh",
    name: "FNS - Ravenna, OH",
    address: "150 Loomis Pkwy, Ravenna, OH 44266, US",
    city: "Ravenna",
    state: "OH",
    type: "Warehouse",
  },
  {
    id: "lockbourne-oh",
    name: "FNS - Lockbourne, OH",
    address: "2190 Creekside Pkwy, Lockbourne, OH 43137, US",
    city: "Lockbourne",
    state: "OH",
    type: "Warehouse",
  },
  {
    id: "portland-or",
    name: "FNS - Portland, OR",
    address: "5515 NE 148th Ave, Suite 302, Portland, OR 97230, US",
    city: "Portland",
    state: "OR",
    type: "Office",
  },
  {
    id: "garden-city-ga",
    name: "FNS - Garden City, GA",
    address: "54 Sonny Perdue Dr, Suite 101, Garden City, GA 31408, US",
    city: "Garden City",
    state: "GA",
    type: "Logistics Hub",
  },
  // Added from the FNS main directory (company-wide location sheet).
  {
    id: "seattle-tacoma-wa",
    name: "FNS - Seattle / Tacoma, WA",
    address: "475 E 19th St, Tacoma, WA 98421, US",
    city: "Tacoma",
    state: "WA",
    type: "Unknown",
  },
  {
    id: "laredo-tx",
    name: "FNS - Laredo, TX",
    address: "8201 Killam Industrial Blvd, Suite #B, Laredo, TX 78045, US",
    city: "Laredo",
    state: "TX",
    type: "Unknown",
  },
  {
    id: "mobile-al",
    name: "FNS - Mobile, AL / Theodore",
    address: "5155 Mobile S. St, Bldg 13, Theodore, AL 36582, US",
    city: "Theodore",
    state: "AL",
    type: "Unknown",
  },
  {
    id: "miami-fl",
    name: "FNS - Miami, FL",
    address: "3340 NW 67th Ave, Suite #820, Miami, FL 33122, US",
    city: "Miami",
    state: "FL",
    type: "Unknown",
  },
  {
    id: "chicago-il",
    name: "FNS - Chicago, IL",
    address: "8755 W Higgins Rd, Suite #1050, Chicago, IL 60631, US",
    city: "Chicago",
    state: "IL",
    type: "Office",
  },
  {
    id: "charleston-sc",
    name: "FNS - Charleston, SC / Summerville",
    address: "168 Portside Park Dr, Suite #C, Summerville, SC 29483, US",
    city: "Summerville",
    state: "SC",
    type: "Unknown",
  },
  {
    id: "new-york-ridgefield-park-nj",
    name: "FNS - New York / Ridgefield Park",
    address: "105 Challenger Rd, Suite #504, Ridgefield Park, NJ 07660, US",
    city: "Ridgefield Park",
    state: "NJ",
    type: "Office",
  },
  {
    id: "cleveland-oh",
    name: "FNS - Cleveland, OH / Streetsboro",
    address: "10242 State Route 43, Streetsboro, OH 44241, US",
    city: "Streetsboro",
    state: "OH",
    type: "Unknown",
  },
  {
    id: "lake-orion-mi",
    name: "FNS - Lake Orion, MI",
    address: "325 W Silverbell Rd, Suite #250, Lake Orion, MI 48359, US",
    city: "Lake Orion",
    state: "MI",
    type: "Unknown",
  },
  {
    id: "toronto-on",
    name: "FNS - Toronto, Canada",
    address: "20 Norelco Dr, North York, ON M9L 2X6, Canada",
    city: "North York",
    state: "ON",
    type: "Unknown",
  },
  {
    id: "vancouver-bc",
    name: "FNS - Vancouver, Canada / Delta",
    address: "3995 27B Ave, Delta, BC V4M 4G5, Canada",
    city: "Delta",
    state: "BC",
    type: "Unknown",
  },
  {
    id: "montreal-qc",
    name: "FNS - Montreal, Canada / Pointe-Claire",
    address: "5500 Route Trans-Canadienne, Pointe-Claire, QC H9R 1B6, Canada",
    city: "Pointe-Claire",
    state: "QC",
    type: "Unknown",
  },
  {
    id: "monterrey-mx",
    name: "FNS - Monterrey, Mexico",
    address:
      "Av. Manuel Gomez Morin 955, Suite 501, Montebello, C.P. 66266, San Pedro Garza Garcia, N.L., Mexico",
    city: "San Pedro Garza Garcia",
    state: "NL",
    type: "Office",
  },
  {
    id: "monterrey-yard-mx",
    name: "FNS - Monterrey Yard, Mexico",
    address: "Moises Saenz 817, Santa Rosa, C.P. 66614, Apodaca, N.L., Mexico",
    city: "Apodaca",
    state: "NL",
    type: "Unknown",
  },
  {
    id: "colon-panama",
    name: "FNS - Colon, Panama",
    address: "Local M1, 4 Altos Plaza, Colon, Republic of Panama",
    city: "Colon",
    state: "Panama",
    type: "Unknown",
  },
];
